; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
framework = picosdk
board = pico
board_build.core = earlephilhower
lib_deps = https://github.com/gbr1/rp2040-encoder-library

[env:pico-tarball]
platform = https://github.com/maxgerhardt/platform-raspberrypi/archive/refs/tags/v1.4.0-gcc14-arduinopico460.tar.gz

[env:pico-git]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#v1.4.0-gcc14-arduinopico460
