name: Check PR

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  cli:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # pin@main
      - name: Check flake
        run: nix flake check

  examples:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        example:
          - external-deps
          - marlin
          - multi-env
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # pin@main
      - name: Check flake
        working-directory: examples/${{ matrix.example }}
        run: nix flake check
