name: Check PR

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@main
      - uses: DeterminateSystems/nix-installer-action@b92f66560d6f97d6576405a7bae901ab57e72b6a # pin@main
        # with:
        #   nix-installer-tag: v0.16.1 # https://github.com/DeterminateSystems/nix-installer/tags
      - uses: DeterminateSystems/magic-nix-cache-action@a76a83091cd8728db8c37312dbdd0eeb1177a6c0 # pin@main
      - uses: DeterminateSystems/flake-checker-action@078f5f7f47ee188aa6cb472527ca5984e195222d # pin@main
      - name: Check flake
        run: nix flake check

  examples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example:
          - external-deps
          - marlin
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@main
      - uses: DeterminateSystems/nix-installer-action@b92f66560d6f97d6576405a7bae901ab57e72b6a # pin@main
        # with:
        #   nix-installer-tag: v0.16.1 # https://github.com/DeterminateSystems/nix-installer/tags
      - uses: DeterminateSystems/magic-nix-cache-action@a76a83091cd8728db8c37312dbdd0eeb1177a6c0 # pin@main
      - name: Check flake
        working-directory: examples/${{ matrix.example }}
        run: nix flake check
